- src/pages/Flows/CreationModal/index.tsx
- src/pages/Flows/DeletionModal/index.tsx
- src/pages/Flows/EditionModal/index.tsx
- src/pages/Flows/index.tsx
- src/pages/Processes/CreationModal/index.tsx
- src/pages/Processes/DeletionModal/index.tsx
- src/pages/Processes/EditionModal/index.tsx
- src/pages/Stages/CreationModal/index.tsx
- src/pages/Stages/DeletionModal/index.tsx
- src/pages/Stages/EditionModal/index.tsx
- src/pages/Units/CreationModal/index.tsx
- src/pages/Units/DeletionModal/index.tsx
- src/pages/Units/EditionModal/index.tsx
- src/pages/ViewProcess/ArchivationModal/index.tsx
- src/pages/ViewProcess/FinalizationModal/index.tsx
- src/pages/ViewProcess/ReturnModal/index.tsx
Closes fga-eps-mds/2023-2-CAPJu-Doc#6
Eu, como servidor, diretor ou administrador. Gostaria de excluir um fluxo e todos os processos inclusos nele para poder não deixar processos acumulados ou avulsos sem fazer parte de um fluxo.
> 10 exclusao de fluxo (Front-end)

- src/pages/Statistics/index.tsx
- src/utils/assets.ts
- src/utils/pdf.ts
US01
Resolução do bug que impedia o componente de ser renderizado na tela.
> US01 - Visualizar quantidade de processos por etapa

- src/pages/Processes/index.tsx
- src/pages/ViewProcess/ArchivationModal/index.tsx
- src/pages/ViewProcess/FinalizationModal/index.tsx
- src/pages/ViewProcess/index.tsx
- src/pages/__tests__/Processes.test.tsx
- src/utils/constants.ts
Closes [#19 - US09 - Atualização e visualização de status do processo](https://github.com/fga-eps-mds/2023-2-CAPJu-Doc/issues/19)
Neste Pull Request, foram implementadas as alterações necessárias para atender aos requisitos da US09. As modificações abrangeram a atualização das cores e do texto em botões, pop-ups e elementos de interface que faziam referência aos diversos estados do processo, incluindo a transição de "Finalizados" para "Concluídos" e "Arquivados" para "Interrompidos". Além disso, foram incorporadas outras mudanças que se originaram da revisão e validação conduzida por Wellington, todas devidamente ajustadas e integradas a este Pull Request.
Os testes da página foram adaptados para acomodar essas mudanças e garantir que a página Processes esteja em conformidade com as novas …
> #19 - US09 - Atualização e visualização de status do processo

- package-lock.json
- src/components/ProcessQuantifier/index.tsx
- src/pages/Statistics/FilteringProcesses/chartUtils.ts
- src/pages/Statistics/FilteringProcesses/index.tsx
- src/services/processManagement/processes/index.ts
- src/types/global.d.ts
- src/utils/constants.ts
US02 - Estatística da quantidade de processos concluídos e interrompidos por fluxo
Nesta Issue, foram feitos os campos a fim de selecionar fluxo, selecionar status (concluídos e interrompidos), as datas de um processo limitadas a 2 anos. Ademais, a partir desta pesquisa um gráfico é gerado. Além disso, é possível visualizar: total de processos, processos concluídos e processos interrompidos. Por fim, é mostrado a pesquisa em uma tabela específica.
> US02 - Estatística da quantidade de processos concluídos e interrompidos por fluxo

- src/pages/Statistics/StepDeadlineReports/index.tsx
- src/types/global.d.ts
- src/utils/pdf.ts
Closes fga-eps-mds/2023-2-CAPJu-Doc#23
Este pull request representa uma significativa melhoria ao incorporar a capacidade de baixar dados em formato PDF e Excel gerados pelas estatísticas de processos, mantendo-se dentro do prazo de validade especificado.
> US05 - PDF e Excel da US14

- src/pages/Statistics/FilteringProcesses/index.tsx
Closes fga-eps-mds/2023-2-CAPJu-Doc#117
Correção de bug
> [BUG] Fluxos não são mostrados ao baixar excel no gráfico de quantidade de processos concluídos / interrompidos #117

- src/pages/Statistics/FilteringProcesses/index.tsx
Closes fga-eps-mds/2023-1-CAPJu-Doc#119
"Altera "esepficadas" para "especificadas"
> [BUG] Erro de ortografia no toast de info do relatório "Visualizar Quantidade de Processos Concluídos / Interrompidos" #119

- src/components/Header/index.tsx
- src/layouts/Private.tsx
- src/pages/Flows/index.tsx
- src/pages/Processes/index.tsx
- src/pages/ProfilesManager/Profiles/index.tsx
- src/pages/ProfilesManager/Requests/index.tsx
- src/pages/Stages/index.tsx
- src/pages/Statistics/index.tsx
- src/pages/Units/index.tsx
Padronizei o espaçamento e posição dos campos e botões nas telas baseado no que sugeri pro PO na US17. Também ajustei o header.
PS: fiz essa branch nova com PR novo por que o outro tinha muito conflito que não consegui resolver com a develop, achei melhor criar do zero pra não zoar nd
> 17 alteracoes visuais

- src/components/Header/index.tsx
- src/hooks/useAuth.tsx
- src/pages/AccountEdition/index.tsx
- src/pages/__tests__/Login.test.tsx
- src/services/__tests__/user.test.tsx
- src/services/user/index.ts
- src/types/global.d.ts
- src/utils/dates.ts
- src/utils/tabs.ts
Closes [#13](https://github.com/fga-eps-mds/2023-2-CAPJu-Doc/issues/13)
Esse Pull Request traz as alterações no frontend da US16. Nele, há mudanças de layout no editar conta, mudança de layout dos serviços, sendo eles agrupados em um ícone, e inclui também as validações dos dados para editar a conta.
- [] Critério 1
- [] Critério 1
- [] Critério 1
- Vamos editar e acrescentar os critérios aqui
| Antes | Depois |
| ----- | ------ |
| ![image](https://github.com/fga-eps-mds/2023-2-CAPJu-Front/assets/110112943/629cb08f-27bf-4e24-a525-13fb1a08bfee) | ![image](https://github.com/fga-eps-mds/2023-2-CAPJu-Front/assets/110112943/2720398c-02b9-4b4d-9738-14643e7321fd) |
> US16 - Agrupamento de Funcionalidades (Frontend)

- src/components/StatsTimeStage/index.tsx
- src/pages/Statistics/FilteringProcesses/components/ExportButtons/index.tsx
- src/pages/Statistics/FilteringProcesses/index.tsx
- src/pages/Statistics/StepDeadlineReports/index.tsx
- src/pages/Statistics/index.tsx
- src/types/global.d.ts
- src/utils/pdf.ts
Closes fga-eps-mds/2023-2-CAPJu-Doc#137
Closes fga-eps-mds/2023-2-CAPJu-Doc#138
Closes fga-eps-mds/2023-2-CAPJu-Doc#140
Closes fga-eps-mds/2023-2-CAPJu-Doc#141
Closes fga-eps-mds/2023-2-CAPJu-Doc#142
Closes fga-eps-mds/2023-2-CAPJu-Doc#145
Esse PR faz as alterações que o PO solicitou, além de corrigir bugs para que seja possível fechar a US05
> Alterações da US05 e bugs do relatório "VIsualizar quantidade de processos concluídos / interormpidos"

- src/pages/Statistics/index.tsx
Closes fga-eps-mds/2023-2-CAPJu-Doc#150
Corrige o bug descrito na issue acima.
> hotfix/ 150

- src/services/__tests__/processManagement/flows.test.tsx
> Testes front

- src/components/DataTable/index.tsx
- src/components/DataUpdateModal/index.tsx
- src/components/FormFields/Input/index.tsx
- src/pages/AccountEdition/index.tsx
- src/pages/PasswordEdition/index.tsx
- src/pages/Processes/EditionModal/index.tsx
- src/pages/Signup/index.tsx
- src/services/processManagement/stage/index.ts
Resolve os bugs 1, 2, 3, 28, 29, 34
Bug 1: E-mail e senha preenchidos automaticamente
Bug 2: O Administrador aparece como perfil de cadastro. Como está configurado o Administrador inicial (primeiro)? A pergunta é importante, pois ele não possui ninguém para autorizá-lo. 
Bug 3: Alterar o texto para: Suas senhas não conferem. 
Bug 28: Não consegui editar etapa (alteração dos dias). 
Bug 29: Não consegui excluir etapa. 
Bug 34:  Está aparecendo a palavra FALSE no campo “com prioridade legal”. 
- [] O Pull Request refere-se a um único assunto, um título claro e uma descrição em frases gramaticalmente corretas e completas.
- [] A ramificação está atualizada com a branch Develop.
- [] Os commits atendem o padrão especificado na política de contribuição.
> Ajuste de bugs da planilha que o Wellington passou

- src/components/StatsTimeStage/index.tsx
Closes fga-eps-mds/2023-2-CAPJu-Doc#160
Resolução do bug que impedia de renderizar a tabela no pdf
> Arrumando o indentificador da tabela no pdf

- src/components/Header/index.tsx
- src/pages/About/index.tsx
- src/pages/Login/index.tsx
- src/pages/ProfilesActionsManager/index.tsx
- src/pages/Signup/index.tsx
botar espaçamento no sobre quando ta logado
tirar marcação de uma das abas quando vc entra em algo do menu do perfil
tirar botao de salvar da parte de permissões de perto do header
voltar olhinho pra ver a senha no cadastro e login
> Ajustes finos

- src/pages/Flows/index.tsx
- src/pages/Processes/EditionModal/index.tsx
- src/pages/Processes/index.tsx
- src/pages/Signup/index.tsx
Closes fga-eps-mds/2023-1-CAPJu-Doc#issue_number
- [] Critério 1
- [] Critério 1
- [] Critério 1
- [] O Pull Request refere-se a um único assunto, um título claro e uma descrição em frases gramaticalmente corretas e completas.
- [] A ramificação está atualizada com a branch Develop.
- [] Os commits atendem o padrão especificado na política de contribuição.
| Antes | Depois |
| ----- | ------ |
| Image 1 | Image 2 |
> Pequenas alterações nos textos e nos parâmetros para editar um processo.

- src/pages/Statistics/index.tsx
- src/utils/pdf.ts
Closes fga-eps-mds/2023-2-CAPJu-Doc#173
- [] Gerar estatistica de processo por etapa selecionando etapa e fluxo
- [] Baixa PDF
> PDF na estatistica de ver processo por etapa bugado

- src/components/Header/index.tsx
- src/components/Pagination/index.tsx
- src/hooks/useAuth.tsx
- src/pages/AccountEdition/index.tsx
- src/pages/ForgotPassword/index.tsx
- src/pages/Login/index.tsx
- src/pages/Processes/CreationModal/index.tsx
- src/pages/Processes/EditionModal/index.tsx
- src/pages/Processes/ImportProcessesModal/index.tsx
- src/pages/Processes/ProcessesFile/VisualizationFileItemsModal/index.tsx
- src/pages/Processes/ProcessesFile/VisualizationFilesModal/index.tsx
- src/pages/Processes/ProcessesFile/index.tsx
- src/services/__tests__/user.test.tsx
- src/services/user/index.ts
Sim. No suposto projeto "quase finalizado" a funcionalidade não havia sido implementada
> Implementação funcionalidade recuperação senha

- src/pages/Flows/index.tsx
- src/pages/Processes/index.tsx
- src/pages/Stages/index.tsx
- src/pages/Units/index.tsx
Closes fga-eps-mds/2023-2-CAPJu-Doc#168
Arrumando bug de pesquisa com a paginação
> Arrumando bug de paginação ao pesquisar nas abas.

- src/pages/__tests__/Stages/Stages.test.tsx
- src/pages/__tests__/Units/Units.test.tsx
- src/services/__tests__/processManagement/flows.test.tsx
- src/services/__tests__/processManagement/process.test.tsx
- src/services/__tests__/processManagement/processesFile.test.tsx
- src/services/__tests__/processManagement/stage.test.tsx
- src/services/__tests__/user.test.tsx
Aumento de cobertura de testes
> Aumento de cobertura de testes
